"""Summarization module for GAD."""

import logging
from abc import ABC, abstractmethod
from typing import Optional

from gad.config import get_settings


logger = logging.getLogger(__name__)


# Summarization prompt template
SUMMARY_PROMPT = """You are a skilled research assistant. Your task is to summarize the following article accurately and comprehensively.

IMPORTANT RULES:
1. Only use information explicitly stated in the provided text.
2. Never add information not present in the original article.
3. If something is unclear or not mentioned, say so rather than guessing.
4. Preserve the author's key arguments and evidence faithfully.

Please structure your summary using the following sections:

## TL;DR
A 2-3 sentence executive summary capturing the main point.

## Problem/Motivation
What problem or question does this article address? Why does it matter?

## Core Ideas/Methods
What are the main concepts, approaches, or methods presented?

## Key Evidence/Examples
What evidence, data, or examples support the main arguments?

## Limitations/Open Questions
What limitations does the author acknowledge? What questions remain unanswered?

## Practical Implications
What are the practical takeaways or applications?

## Key Quotes
2-3 notable direct quotes from the article (with quotation marks).

---

ARTICLE TEXT:
{text}
"""


class Summarizer(ABC):
    """Abstract base class for summarizers."""

    @abstractmethod
    def summarize(self, text: str, title: Optional[str] = None) -> str:
        """Generate a summary of the given text.

        Args:
            text: The article text to summarize.
            title: Optional title for context.

        Returns:
            Markdown-formatted summary.
        """
        pass


class MockSummarizer(Summarizer):
    """Mock summarizer for testing without API calls."""

    def summarize(self, text: str, title: Optional[str] = None) -> str:
        """Generate a heuristic summary without LLM.

        Creates a basic summary using the first few sentences
        and some statistics about the content.

        Args:
            text: The article text to summarize.
            title: Optional title for context.

        Returns:
            Markdown-formatted mock summary.
        """
        logger.info("Using mock summarizer (no API key configured)")

        # Get basic stats
        words = text.split()
        word_count = len(words)
        sentences = text.replace("!", ".").replace("?", ".").split(".")
        sentences = [s.strip() for s in sentences if s.strip()]

        # Extract first few sentences for TL;DR
        first_sentences = " ".join(sentences[:3]) if sentences else "No content available."
        if len(first_sentences) > 500:
            first_sentences = first_sentences[:500] + "..."

        # Get a sample quote (first substantial sentence)
        quote = ""
        for s in sentences:
            if len(s) > 50:
                quote = f'"{s}"'
                break

        title_text = title or "Untitled Article"

        return f"""# Summary: {title_text}

> **Note**: This is a mock summary generated without an LLM. Configure OPENAI_API_KEY for AI-powered summaries.

## TL;DR
{first_sentences}

## Problem/Motivation
*[Mock summary - content analysis not available without LLM]*

This article contains approximately {word_count:,} words and {len(sentences)} sentences.

## Core Ideas/Methods
*[Mock summary - detailed analysis requires LLM]*

## Key Evidence/Examples
*[Mock summary - evidence extraction requires LLM]*

## Limitations/Open Questions
*[Mock summary - critical analysis requires LLM]*

## Practical Implications
*[Mock summary - practical takeaways require LLM analysis]*

## Key Quotes
{quote if quote else "*[No substantial quotes extracted]*"}

---
*Generated by GAD Mock Summarizer*
"""


class OpenAISummarizer(Summarizer):
    """Summarizer using OpenAI API."""

    def __init__(self, api_key: str, model: str = "gpt-4o-mini"):
        """Initialize the OpenAI summarizer.

        Args:
            api_key: OpenAI API key.
            model: Model name to use.
        """
        self.api_key = api_key
        self.model = model

        # Import here to avoid requiring openai when not used
        try:
            from openai import OpenAI

            self.client = OpenAI(api_key=api_key)
        except ImportError:
            raise ImportError(
                "openai package is required for OpenAI summarization. "
                "Install with: pip install openai"
            )

    def summarize(self, text: str, title: Optional[str] = None) -> str:
        """Generate a summary using OpenAI API.

        Args:
            text: The article text to summarize.
            title: Optional title for context.

        Returns:
            Markdown-formatted summary.
        """
        settings = get_settings()

        # Truncate if too long
        if len(text) > settings.max_input_chars:
            logger.warning(
                f"Text too long ({len(text)} chars), truncating to {settings.max_input_chars}"
            )
            text = text[: settings.max_input_chars] + "\n\n[Content truncated...]"

        prompt = SUMMARY_PROMPT.format(text=text)

        try:
            logger.info(f"Calling OpenAI API with model {self.model}")
            response = self.client.chat.completions.create(
                model=self.model,
                messages=[
                    {
                        "role": "system",
                        "content": "You are a helpful research assistant that creates accurate, well-structured summaries.",
                    },
                    {"role": "user", "content": prompt},
                ],
                temperature=0.3,  # Lower temperature for more factual output
                max_tokens=2000,
            )

            summary = response.choices[0].message.content or ""

            # Add title header if provided
            if title and not summary.startswith(f"# {title}"):
                summary = f"# Summary: {title}\n\n{summary}"

            return summary

        except Exception as e:
            logger.error(f"OpenAI API error: {e}")
            raise RuntimeError(f"Failed to generate summary: {e}") from e


def get_summarizer() -> Summarizer:
    """Get the appropriate summarizer based on configuration.

    Returns OpenAISummarizer if OPENAI_API_KEY is set,
    otherwise returns MockSummarizer.

    Returns:
        A Summarizer instance.
    """
    settings = get_settings()

    if settings.openai_api_key:
        logger.info("Using OpenAI summarizer")
        return OpenAISummarizer(
            api_key=settings.openai_api_key,
            model=settings.model,
        )
    else:
        logger.info("No OPENAI_API_KEY found, using mock summarizer")
        return MockSummarizer()
